
1:= `date`

default: 
	javac *.java -classpath "/home/xpat/Universidad/Tercero/FR/Practicas/Practicas/Practica 2/FR-ugr/TicToe/src/tictoe/"
clean:
	rm *.class
git: 
	make clean
	git add .
	git commit -m "$1" 
	git push
